version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "semiannually"
    cooldown:
      default-days: 20
    groups:
      github-actions:
        patterns:
          - "*"

  # Prevent updates of requirements files used only for testing.
  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "semiannually"
    ignore:
      - dependency-name: "*"
